
### Get all contacts
GET http://cse341-vcsw.onrender.com/contacts


### Get contact by id
GET http://cse341-vcsw.onrender.com/contacts/69176a573398a749a47a8779


### Create contact
POST http://cse341-vcsw.onrender.com/contacts
Content-Type: application/json

{
"firstName":"Caden",
"lastName": "Smith",
"email": "casm@example.com",
"city": "Rhode Island",
"country": "United States",
"instagram": "casm_ins",
"facebook": "Caden Smith"
}

###Update a contact
PUT http://cse341-vcsw.onrender.com/contacts/69176a573398a749a47a8779
Content-Type: application/json

{
"firstName":"Caden",
"lastName": "Smith",
"email": "casm@example.com",
"city": "Rhode Island",
"country": "United States",
"instagram": "casm_ins",
"facebook": "Caden Smith"
}

###Delete a contact
DELETE http://cse341-vcsw.onrender.com/contacts/6917865f055f6d207cb878fd