
### Get all contacts
GET http://project-cse341-01wr.onrender.com/books


### Get contact by id
GET http://project-cse341-01wr.onrender.com/connection/69176a573398a749a47a8779


### Create contact
POST http://project-cse341-01wr.onrender.com/connection
Content-Type: application/json

{
"firstName":"Caden",
"lastName": "Smith",
"email": "casm@example.com",
"city": "Rhode Island",
"country": "United States",
"instagram": "casm_ins",
"facebook": "Caden Smith"
}

###Update a contact
PUT http://project-cse341-01wr.onrender.com/69176a573398a749a47a8779
Content-Type: application/json

{
"firstName":"Caden",
"lastName": "Smith",
"email": "casm@example.com",
"city": "Rhode Island",
"country": "United States",
"instagram": "casm_ins",
"facebook": "Caden Smith"
}

###Delete a contact
DELETE http://project-cse341-01wr.onrender.com/connection/6917865f055f6d207cb878fd